name: packlodge-system
main: app.ccls.packlodge.Main
version: 0.0.4
api-version: 1.21
authors: [ 5q12 ]
website: https://5q12.ccls.icu/packlodge
commands:
  seen:
  playtime:
  location:
  modpack:
  psd:
  psget: