name: packlodge-system
main: app.ccls.packlodge.Main
version: 1.0
api-version: 1.20
authors: [ 5q12 ]
website: https://5q12.ccls.icu
commands:
  seen:
  playtime:
  location:
  modpack:
  psd: